const FULL_CAPTURE_BASE = Object.freeze({
  subjectCount: '1',
  framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
  angleId: { byZh: '平視高度鏡頭' },
  orbitId: { byZh: '左前 45 度' },
  locationId: { byZh: '室內：英倫復古窗邊房間' },
  styleId: { byZh: '上田義彥｜靜默自然暗調' },
  lensId: { byZh: '50mm 標準鏡頭 (Standard)' },
  filmId: { byZh: '富士 Provia 清透明亮' },
});

export const AI_PROMPT_LENGTH_FIXTURES = Object.freeze([
  {
    id: 'normal-separates',
    policy: 'normal',
    seed: 'ai-length-normal-separates-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      bodyTypeId: { byZh: '一般基本體型' },
      hairstyleId: { byZh: '柔波：深側分' },
      hairColorId: { byZh: '栗子棕' },
      topId: { byZh: '領帶襯衫' },
      topColorId: { byZh: '白色' },
      skirtId: { byZh: 'A 字短裙' },
      bottomColorId: { byZh: '黑色' },
      outerwearId: { byZh: '西裝外套' },
      outerwearColorId: { byZh: '深灰色' },
      shoesId: { byZh: '樂福鞋' },
      shoesColorId: { byZh: '黑色' },
    },
    requiredFragments: ['blazer', 'a-line mini skirt'],
  },
  {
    id: 'complete-look-latex',
    policy: 'completeLook',
    seed: 'ai-length-complete-look-latex-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      outfitPresetId: { byZh: '套裝：亮面乳膠束帶' },
      outfitPresetPrimaryColorId: { byZh: '黑色' },
      outfitPresetContrastColorId: { byZh: '紅色' },
    },
    requiredFragments: ['mirror-polished latex full-body catsuit'],
  },
  {
    id: 'complete-look-special',
    policy: 'completeLook',
    seed: 'ai-length-complete-look-special-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      specialOutfitId: { byZh: '白色短袖背心格紋迷你裙白蕾絲襪造型' },
    },
    requiredFragments: ['plaid'],
  },
  {
    id: 'complete-look-dress',
    policy: 'completeLook',
    seed: 'ai-length-complete-look-dress-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      dressId: { byZh: '連身：短版｜一字領哥德迷你洋裝' },
      dressColorId: { byZh: '黑色' },
    },
    requiredFragments: ['gothic mini dress'],
  },
  {
    id: 'character-card-jiwoo',
    policy: 'characterCard',
    seed: 'ai-length-character-card-jiwoo-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      characterProfileId: 'character-jiwoo',
    },
    requiredFragments: [
      'A 20-year-old adult East Asian woman',
      'small heart-oval face with a fine pointed chin',
      'wide-set gray-hazel almond eyes with lifted corners',
      'narrow-bridge rounded-tip nose',
      'full coral-brick cupid-bow lips',
      'extremely long natural black hair',
      'black off-shoulder gothic dress',
      'black pointed-toe stiletto pumps',
    ],
  },
  {
    id: 'character-card-sui',
    policy: 'characterCard',
    seed: 'ai-length-character-card-sui-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      characterProfileId: 'character-sui',
    },
    requiredFragments: [
      'A 20-year-old adult East Asian woman',
      'long narrow heart-oval face with a pointed chin',
      'downturned amber almond eyes with heavy upper lids',
      'natural freckles across cheeks and nose bridge',
      'small rose-coral cupid-bow lips',
      'glossy natural black long wavy hair',
      'cream ribbed knit camisole',
      'medium-dark blue straight-leg jeans',
      'mustard yellow oversized knit cardigan',
      'brown leather ankle boots',
      'delicate gold necklace',
    ],
  },
  {
    id: 'character-card-half-face-pressure',
    policy: 'characterCard',
    seed: 'ai-length-character-card-half-face-v1',
    locks: {
      subjectCount: '1',
      characterProfileId: 'character-jiwoo',
      characterCardHairVariantId: 'highlight-streaks',
      framingId: { byZh: '半臉傾斜特寫' },
      angleId: { byZh: '平視高度鏡頭' },
      orbitId: { byZh: '左前 45 度' },
      locationId: { byZh: '戶外：高級飯店陽台城市河景' },
      styleId: { byZh: '荒木經惟｜私寫真親密' },
      lensId: { byZh: '24mm 廣角' },
      opticalEffectId: { byZh: '肥皂泡散景 Soap-bubble Bokeh' },
      filmId: { byZh: '高銳利快照黑位' },
    },
    requiredFragments: [
      'small heart-oval face with a fine pointed chin',
      'keep the original hair identity',
      'black off-shoulder gothic dress',
      'luxury hotel balcony river-view terrace',
      'glass railing',
      'Nobuyoshi Araki-inspired',
      '24mm wide-angle lens',
      'soap-bubble bokeh rendering',
      'high-acutance snapshot rendering',
    ],
  },
  {
    id: 'canonical-pose-pressure',
    policy: 'normal',
    seed: 'ai-length-canonical-pose-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '自然站姿' },
      poseHandId: { byZh: '單手摸下巴' },
      poseHeadId: { byZh: '頭部微微側傾' },
      poseAnchorId: { byZh: '肩背倚靠現有垂直面' },
    },
    requiresCanonicalPose: true,
  },
  {
    id: 'half-face-boundary',
    policy: 'normal',
    seed: 'ai-length-half-face-v1',
    locks: {
      ...FULL_CAPTURE_BASE,
      framingId: { byZh: '半臉傾斜特寫' },
      topId: { byZh: '領帶襯衫' },
      topColorId: { byZh: '白色' },
    },
    requiredFragments: ['collared shirt'],
  },
  {
    id: 'duo-excluded-boundary',
    policy: null,
    seed: 'ai-length-duo-boundary-v1',
    mode: 'duo',
    locks: {
      subjectCount: '2',
      framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
      duoPoseId: { byZh: '充滿情慾的時尚寫真' },
      duoPoseBaseId: { byZh: '站姿' },
      locationId: { byZh: '室內：英倫復古窗邊房間' },
    },
    excludedFromBudget: true,
  },
]);
