/**
 * Phase-1 desired-output fixtures for the PAGE1 composition visibility work.
 *
 * These cases intentionally do not run through the current renderers yet. They
 * pin the approved wardrobe, pose, scene, raw-selection, and full-body-reference
 * outcomes so later phases can activate one behavior group at a time.
 */
export const COMPOSITION_VISIBILITY_REGRESSION_FIXTURES = Object.freeze([
  {
    id: 'head-shoulders-pose-scene-pressure',
    coverage: ['single', 'dress', 'pose', 'anchor', 'scene', 'headShoulders'],
    seed: 'composition-visibility-head-shoulders-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '特寫鏡頭 (Close-Up)' },
      bodyTypeId: { byZh: '小隻精緻身形' },
      hairstyleId: { byZh: '齊瀏海圓弧鮑伯' },
      eyewearId: { byZh: '太陽眼鏡' },
      eyewearColorId: { byZh: '白色' },
      eyewearPlacementId: { byZh: '戴在頭頂' },
      dressId: { byZh: '連身：短版｜一字領哥德迷你洋裝' },
      dressColorId: { byZh: '米白色' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '一腳向前點地' },
      poseHandId: { byZh: '一手扶腰一手自然放下' },
      poseHeadId: { byZh: '頭部微微側傾' },
      poseAnchorId: { byZh: '鏡面不鏽鋼立方台' },
      locationId: { byZh: '室內：復古美式 Diner' },
    },
    expectedProjection: {
      bucket: 'headShoulders',
      preserveRawLockKeys: ['dressId', 'poseBaseId', 'poseArrangementId', 'poseHandId', 'poseHeadId', 'poseAnchorId', 'locationId'],
      mainPrompt: {
        includes: ['off-white off-shoulder gothic dress', 'retro American diner', 'red leather bench seating', 'chrome'],
        excludes: [
          'mini dress',
          'short hem',
          'one hand on the waist or hip line',
          'delicate extended standing stance',
          'mirrored stainless-steel cube plinth',
          'softly blurred',
          'bokeh',
          'shallow depth of field',
        ],
        poseMode: 'omit',
        poseIncludes: [],
        poseExcludes: [
          'one hand on the waist or hip line',
          'delicate extended standing stance',
          'mirrored stainless-steel cube plinth',
        ],
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['off-white off-shoulder gothic mini dress', 'short hem'],
      },
    },
  },
  {
    id: 'chest-up-layered-separates',
    coverage: ['single', 'separates', 'outerwear', 'chestUp'],
    seed: 'composition-visibility-chest-up-layers-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '胸上特寫' },
      topId: { byZh: '棉質細肩背心' },
      pantsId: { byZh: '直筒牛仔褲' },
      outerwearId: { byZh: '丹寧外套' },
      legwearId: { byZh: '羅紋短襪' },
      shoesId: { byZh: '尖頭細跟高跟鞋' },
    },
    expectedProjection: {
      bucket: 'chestUp',
      preserveRawLockKeys: ['topId', 'pantsId', 'outerwearId', 'legwearId', 'shoesId'],
      mainPrompt: {
        includes: ['cotton camisole', 'denim jacket'],
        excludes: ['straight-leg jeans', 'ribbed ankle socks', 'pointed-toe stiletto heels'],
        poseMode: 'visibleFragments',
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['straight-leg jeans', 'ribbed ankle socks', 'pointed-toe stiletto heels'],
      },
    },
  },
  {
    id: 'chest-up-visible-pose-fragments',
    coverage: ['single', 'pose', 'prop', 'anchor', 'chestUp'],
    seed: 'composition-visibility-chest-up-pose-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '胸上特寫' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '上身大幅度前傾' },
      poseHandId: { byZh: '全無' },
      posePropId: { byZh: '塗口紅｜自由妝感' },
      poseHeadId: { byZh: '頭部微微側傾' },
      poseAnchorId: { byZh: '肩背倚靠現有垂直面' },
    },
    expectedProjection: {
      bucket: 'chestUp',
      preserveRawLockKeys: ['poseBaseId', 'poseArrangementId', 'poseHandId', 'posePropId', 'poseHeadId', 'poseAnchorId'],
      mainPrompt: {
        includes: [
          'head slightly tilted',
          'applying lipstick directly to the lips',
          'deep forward lean from the waist',
          'shoulder and the upper back resting against an existing vertical surface',
        ],
        excludes: ['standing pose', 'lower body', 'feet', 'foot'],
        poseMode: 'visibleFragments',
        poseIncludes: [
          'head slightly tilted',
          'applying lipstick directly to the lips',
          'deep forward lean from the waist',
          'shoulder and the upper back resting against an existing vertical surface',
        ],
        poseExcludes: ['standing pose', 'lower body', 'feet', 'foot'],
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
    },
  },
  {
    id: 'medium-pose-base-fallback',
    coverage: ['single', 'pose', 'prop', 'anchor', 'mediumWaist'],
    seed: 'composition-visibility-medium-pose-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '中景鏡頭 (Medium Shot)' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '一腳向前點地' },
      poseHandId: { byZh: '單手摸下巴' },
      posePropId: { byZh: '全無' },
      poseHeadId: { byZh: '下巴微抬' },
      poseAnchorId: { byZh: '鏡面不鏽鋼立方台' },
    },
    expectedProjection: {
      bucket: 'mediumWaist',
      preserveRawLockKeys: ['poseBaseId', 'poseArrangementId', 'poseHandId', 'posePropId', 'poseHeadId', 'poseAnchorId'],
      mainPrompt: {
        includes: ['chin slightly raised', 'one hand touching the chin', 'standing pose'],
        excludes: ['one foot pointed forward', 'rear leg holding the body weight', 'mirrored stainless-steel cube plinth'],
        poseMode: 'visibleFragments',
        poseIncludes: ['chin slightly raised', 'one hand touching the chin', 'standing pose'],
        poseExcludes: ['one foot pointed forward', 'rear leg holding the body weight', 'mirrored stainless-steel cube plinth'],
        sceneMode: 'conciseSource',
        addDepthEffect: false,
      },
    },
  },
  {
    id: 'cowboy-pose-without-foot-action',
    coverage: ['single', 'pose', 'anchor', 'cowboyKnee'],
    seed: 'composition-visibility-cowboy-pose-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '牛仔中景 (Cowboy Shot)' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '一腳向前點地' },
      poseHandId: { byZh: '一手扶腰一手自然放下' },
      posePropId: { byZh: '全無' },
      poseHeadId: { byZh: '頭部微微側傾' },
      poseAnchorId: { byZh: '鏡面不鏽鋼立方台' },
    },
    expectedProjection: {
      bucket: 'cowboyKnee',
      preserveRawLockKeys: ['poseBaseId', 'poseArrangementId', 'poseHandId', 'posePropId', 'poseHeadId', 'poseAnchorId'],
      mainPrompt: {
        includes: ['head slightly tilted', 'one hand on the waist or hip line', 'standing pose', 'mirrored stainless-steel cube plinth'],
        excludes: ['one foot pointed forward', 'rear leg holding the body weight'],
        poseMode: 'visibleFragments',
        poseIncludes: ['head slightly tilted', 'one hand on the waist or hip line', 'standing pose', 'mirrored stainless-steel cube plinth'],
        poseExcludes: ['one foot pointed forward', 'rear leg holding the body weight'],
        sceneMode: 'conciseSource',
        addDepthEffect: false,
      },
    },
  },
  {
    id: 'medium-hidden-lower-hand-action',
    coverage: ['single', 'pose', 'hand', 'mediumWaist'],
    seed: 'composition-visibility-medium-lower-hand-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '中景鏡頭 (Medium Shot)' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '全無' },
      poseHandId: { byZh: '雙手收在腹前' },
      posePropId: { byZh: '全無' },
      poseHeadId: { byZh: '全無' },
      poseAnchorId: { byZh: '全無' },
    },
    expectedProjection: {
      bucket: 'mediumWaist',
      preserveRawLockKeys: ['poseBaseId', 'poseArrangementId', 'poseHandId', 'posePropId', 'poseHeadId', 'poseAnchorId'],
      mainPrompt: {
        includes: ['standing pose'],
        excludes: ['lower abdomen', 'near the knees', 'compact low pose'],
        poseMode: 'visibleFragments',
        poseIncludes: ['standing pose'],
        poseExcludes: ['lower abdomen', 'near the knees', 'compact low pose'],
        sceneMode: 'conciseSource',
        addDepthEffect: false,
      },
    },
  },
  {
    id: 'medium-dress-visible-identity',
    coverage: ['single', 'dress', 'mediumWaist'],
    seed: 'composition-visibility-medium-dress-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '中景鏡頭 (Medium Shot)' },
      dressId: { byZh: '連身：短版｜一字領哥德迷你洋裝' },
      dressColorId: { byZh: '米白色' },
    },
    expectedProjection: {
      bucket: 'mediumWaist',
      preserveRawLockKeys: ['dressId', 'dressColorId'],
      mainPrompt: {
        includes: ['off-white off-shoulder gothic dress'],
        excludes: ['short hem'],
        poseMode: 'visibleFragments',
        sceneMode: 'conciseSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['off-white off-shoulder gothic mini dress', 'short hem'],
      },
    },
  },
  {
    id: 'cowboy-conditional-thigh-highs',
    coverage: ['single', 'separates', 'legwear', 'shoes', 'cowboyKnee'],
    seed: 'composition-visibility-cowboy-legwear-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '牛仔中景 (Cowboy Shot)' },
      topId: { byZh: '棉質細肩背心' },
      skirtId: { byZh: '百褶短裙' },
      legwearId: { byZh: '蕾絲大腿絲襪' },
      shoesId: { byZh: '高跟鞋' },
    },
    expectedProjection: {
      bucket: 'cowboyKnee',
      preserveRawLockKeys: ['topId', 'skirtId', 'legwearId', 'shoesId'],
      mainPrompt: {
        includes: ['cotton camisole', 'pleated mini skirt'],
        conditionalIncludes: ['lace-top thigh-high stockings'],
        excludes: ['stiletto pumps'],
        poseMode: 'visibleFragments',
        sceneMode: 'conciseSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['lace-top thigh-high stockings', 'stiletto pumps'],
      },
    },
  },
  {
    id: 'chest-up-outfit-preset',
    coverage: ['single', 'outfitPreset', 'chestUp'],
    seed: 'composition-visibility-preset-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '胸上特寫' },
      outfitPresetId: { byZh: '套裝：透視背心漆皮短褲長靴' },
      outfitPresetPrimaryColorId: { byZh: '白色' },
    },
    expectedProjection: {
      bucket: 'chestUp',
      preserveRawLockKeys: ['outfitPresetId', 'outfitPresetPrimaryColorId'],
      mainPrompt: {
        includes: ['cropped sheer fitted tank top', 'strapless lace bra layer'],
        excludes: ['exposed navel and abdomen', 'low-rise glossy micro shorts', 'knee-high leather boots'],
        poseMode: 'visibleFragments',
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['exposed navel and abdomen', 'low-rise glossy micro shorts', 'knee-high leather boots'],
      },
    },
  },
  {
    id: 'chest-up-special-outfit-mixed-fragment',
    coverage: ['single', 'specialOutfit', 'chestUp'],
    seed: 'composition-visibility-special-outfit-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '胸上特寫' },
      specialOutfitId: { byZh: '白襯衫黑色長裙細領帶造型' },
    },
    expectedProjection: {
      bucket: 'chestUp',
      preserveRawLockKeys: ['specialOutfitId'],
      mainPrompt: {
        includes: ['white long-sleeve pointed-collar button-up shirt', 'slim black scarf tie or lanyard'],
        excludes: ['ankle-length', 'black soft shoulder tote', 'black lace-up leather shoes'],
        poseMode: 'visibleFragments',
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['voluminous black ankle-length skirt', 'black soft shoulder tote', 'black lace-up leather shoes'],
      },
    },
  },
  {
    id: 'face-detail-character-card-preservation',
    coverage: ['single', 'characterCard', 'faceDetail', 'fullBodyReference', 'selectionPreservation'],
    seed: 'composition-visibility-character-card-v1',
    locks: {
      subjectCount: '1',
      characterProfileId: 'character-rika',
      framingId: { byZh: '臉部特寫' },
    },
    expectedProjection: {
      bucket: 'faceDetail',
      preserveRawLockKeys: ['characterProfileId'],
      mainPrompt: {
        includes: ['11_Rika', 'permanent identity anchors'],
        excludes: ['low-rise light-wash blue jeans', 'white low-top sneakers'],
        poseMode: 'omit',
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['11_Rika', 'low-rise light-wash blue jeans', 'white low-top sneakers'],
      },
    },
  },
  {
    id: 'face-detail-full-body-wardrobe-restoration',
    coverage: ['single', 'separates', 'faceDetail', 'fullBodyReference', 'selectionPreservation'],
    seed: 'composition-visibility-face-full-body-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '臉部特寫' },
      topId: { byZh: '襯衫' },
      skirtId: { byZh: '百褶短裙' },
      outerwearId: { byZh: '丹寧外套' },
      legwearId: { byZh: '羅紋短襪' },
      shoesId: { byZh: 'Samba OG' },
    },
    expectedProjection: {
      bucket: 'faceDetail',
      preserveRawLockKeys: ['topId', 'skirtId', 'outerwearId', 'legwearId', 'shoesId'],
      mainPrompt: {
        excludes: ['shirt', 'pleated mini skirt', 'denim jacket', 'ribbed ankle socks', 'samba og'],
        poseMode: 'omit',
        sceneMode: 'compactSource',
        addDepthEffect: false,
      },
      fullBodyCharacterPrompt: {
        includes: ['shirt', 'pleated mini skirt', 'denim jacket', 'ribbed ankle socks', 'samba og'],
      },
    },
  },
  {
    id: 'medium-duo-role-visibility',
    coverage: ['duo', 'separates', 'outerwear', 'mediumWaist'],
    seed: 'composition-visibility-duo-v1',
    locks: {
      subjectCount: '2',
      framingId: { byZh: '中景鏡頭 (Medium Shot)' },
      topAId: { byZh: '棉質細肩背心' },
      pantsAId: { byZh: '直筒牛仔褲' },
      outerwearAId: { byZh: '丹寧外套' },
      legwearAId: { byZh: '羅紋短襪' },
      shoesAId: { byZh: '低筒球鞋' },
      topBId: { byZh: '襯衫' },
      pantsBId: { byZh: '西裝長褲' },
      outerwearBId: { byZh: '西裝外套' },
      legwearBId: { byZh: '長筒襪' },
      shoesBId: { byZh: '樂福鞋' },
    },
    expectedProjection: {
      bucket: 'mediumWaist',
      preserveRawLockKeys: [
        'topAId',
        'pantsAId',
        'outerwearAId',
        'legwearAId',
        'shoesAId',
        'topBId',
        'pantsBId',
        'outerwearBId',
        'legwearBId',
        'shoesBId',
      ],
      mainPrompt: {
        includes: ['cotton camisole', 'straight-leg jeans', 'denim jacket', 'shirt', 'tailored trousers', 'blazer'],
        excludes: ['ribbed ankle socks', 'low-top sneakers', 'knee-high socks', 'loafers'],
        poseMode: 'visibleFragments',
        sceneMode: 'conciseSource',
        addDepthEffect: false,
      },
    },
  },
  {
    id: 'full-body-complete-composition',
    coverage: ['single', 'separates', 'pose', 'anchor', 'scene', 'fullBody'],
    seed: 'composition-visibility-full-body-v1',
    locks: {
      subjectCount: '1',
      framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
      topId: { byZh: '棉質細肩背心' },
      skirtId: { byZh: '百褶短裙' },
      legwearId: { byZh: '羅紋短襪' },
      shoesId: { byZh: '高跟鞋' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '一腳向前點地' },
      poseHandId: { byZh: '一手扶腰一手自然放下' },
      poseAnchorId: { byZh: '鏡面不鏽鋼立方台' },
      locationId: { byZh: '室內：復古美式 Diner' },
    },
    expectedProjection: {
      bucket: 'fullBody',
      preserveRawLockKeys: ['topId', 'skirtId', 'legwearId', 'shoesId', 'poseArrangementId', 'poseHandId', 'poseAnchorId', 'locationId'],
      mainPrompt: {
        includes: [
          'cotton camisole',
          'pleated mini skirt',
          'ribbed ankle socks',
          'stiletto pumps',
          'delicate extended standing stance',
          'mirrored stainless-steel cube plinth',
          'retro American diner booth',
        ],
        poseMode: 'fullCanonical',
        poseIncludes: [
          'one hand on the waist or hip line',
          'delicate extended standing stance',
          'one foot pointed forward',
          'mirrored stainless-steel cube plinth',
        ],
        poseExcludes: [],
        sceneMode: 'fullSource',
        addDepthEffect: false,
      },
    },
  },
]);
