export const FIXED_COMPOSITION_SHARED_STRUCTURE_EN = 'fixed-set rule: stable selected room architecture; vary only subject placement, pose, crop, camera distance, camera orbit, lighting, and mood inside the same real-scale set; keep adult scale believable against furniture, fixtures, and props; avoid enlarging the subject or shrinking set anchors';
const OUTDOOR_FIXED_COMPOSITION_SHARED_STRUCTURE_EN = 'fixed-set rule: stable selected outdoor architecture; vary only subject placement, pose, crop, lighting, mood, and selected background life state inside the same real-scale set; keep adult scale believable against roads, stairs, rails, poles, buildings, and distant background anchors; avoid enlarging the subject or shrinking set anchors';
export const OUTDOOR_FIXED_SET_GROUP_ID = 'outdoor-fixed-scene';

export const FIXED_COMPOSITION_SET_OPTIONS = [
  { id: 'none', zh: '全無', en: 'none', desc: '不使用固定構圖場景。', meta: { tags: ['none'] } },
  {
    id: 'concrete-wall-chesterfield-sofa',
    zh: '清水模牆面沙發棚',
    setGroupId: 'sofa-lounge',
    en: 'The portrait takes place inside a real-scale compact living-room editorial set, not a flat backdrop and not a tight subject portrait. Treat the fixed set as the primary composition: a raw concrete wall fills the back plane, a large brown vintage Chesterfield leather sofa occupies most of the lower set space, with thick rolled armrests, high tufted backrest, deep adult-sized seat cushions, worn leather texture, and believable adult-scale furniture clearly visible. Bare sculptural dry branches stand beside the sofa, and a normal-height low coffee table sits in front with art books, a cup, a small lamp, textured cushions, and quiet modern-retro interior props as readable interaction anchors. Use a medium-wide editorial camera position approximately 3 to 4 meters away from the sofa, pulled back enough to show the subject inside the room and preserve the subject-to-furniture scale. The selected camera angle and orbit may vary the viewpoint around the same fixed living-room set, but must not replace the set, collapse into a tight portrait, or lose the sofa, concrete wall, dry branches, and coffee table as recognizable anchors',
    integrityEn: 'preserve anchors: raw-concrete wall, brown Chesterfield sofa, branch-side area, coffee-table foreground; keep their relative positions stable',
    replacementGuardEn: 'avoid plain studio backdrop, bedroom, cafe, outdoor street, or unrelated room',
    desc: '灰色清水模牆、枯樹枝、棕色復古 Chesterfield 皮沙發、茶几書本與桌燈構成的固定 editorial set。',
    aspectRatioId: '1:1',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'indoor', 'sofa_set', 'square_set'] },
  },
  {
    id: 'limewash-black-velvet-industrial-sofa',
    zh: '暖灰泥黑絲絨工業沙發棚',
    setGroupId: 'sofa-lounge',
    en: 'The portrait takes place inside a real-scale compact editorial lounge set with a warm ivory limewash plaster wall, a large black velvet sofa, and an industrial low coffee table as the primary fixed anchors, not a flat backdrop and not a tight subject portrait. Treat the fixed set as the primary composition: the warm ivory limewash plaster wall fills the back plane, with subtle hand-troweled texture, soft tonal variation, and no form-tie holes or exposed aggregate. The large black velvet sofa occupies most of the lower set space, with rounded armrests, deep adult-sized seat cushions, soft matte velvet upholstery, visible velvet nap, subtle directional fabric sheen, and believable adult-scale furniture clearly visible, not leather or glossy vinyl. A simple black-framed abstract artwork or irregular antique-brass mirror sits on the wall as a vertical anchor. The industrial low coffee table sits in front, made of black metal frame and aged dark wood or dark metal tabletop, holding art books, a ceramic cup, a clear glass, and a compact brass or black-metal table lamp as readable interaction props. Use a medium-wide editorial camera position approximately 3 to 4 meters away from the sofa, pulled back enough to show the subject inside the room and preserve the subject-to-furniture scale. The selected camera angle and orbit may vary the viewpoint around the same fixed black-velvet lounge set, but must not replace the set, collapse into a tight portrait, or lose the limewash wall, black velvet sofa, wall-art or mirror zone, and industrial coffee table as recognizable anchors',
    integrityEn: 'preserve anchors: warm limewash plaster wall, black velvet sofa, wall-art or mirror zone, industrial coffee-table foreground; keep their relative positions stable',
    replacementGuardEn: 'avoid raw concrete set, brown leather sofa, bare dry-branch decor, plain studio backdrop, bedroom, cafe, outdoor street, or unrelated room',
    desc: '暖象牙灰泥牆、黑色絲絨沙發、牆面畫作或金屬鏡、黑鐵工業風茶几與桌燈構成的固定 editorial lounge set。',
    aspectRatioId: '1:1',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'indoor', 'sofa_set', 'black_velvet_sofa_set', 'industrial_lounge_set', 'square_set'] },
  },
  {
    id: 'luxury-hotel-window-nyc',
    zh: '高級飯店落地窗都市夜景',
    setGroupId: 'hotel-window',
    en: 'The portrait takes place inside a real-scale luxury hotel room editorial set, not a flat backdrop and not a tight subject portrait. Treat the fixed set as the primary composition: an oversized near-wall-to-wall panoramic floor-to-ceiling glass wall dominates the back plane as one broad mostly uninterrupted glass plane overlooking a New York-style high-rise skyline. The glass should feel open, expansive, and lightly reflective, with only a few slim structural seams near the far edges if needed. Avoid grid-like window panels, heavy black frames, boxed window sections, many repeated dividers, balcony doors, or apartment-style segmented windows. A hotel bed with soft white rumpled bedding occupies the lower room plane, with pillows, a bedside table, wine glass, open book, warm hotel lamp, curtain edges, and subtle room-depth props as readable interaction anchors. Use a medium-wide editorial camera position approximately 3 to 5 meters away from the bed and glass wall, pulled back enough to show the subject inside the room and preserve the subject-to-bed and subject-to-window scale. The viewpoint may vary around the same fixed hotel-window set, but must not replace the set, collapse into a tight portrait, or lose the panoramic glass wall, New York skyline, bed or bedding, and warm bedside lamp as recognizable anchors',
    integrityEn: 'preserve anchors: broad panoramic glass wall, New York skyline depth, bed/bedding foreground, bedside lamp/table zone; keep their relative positions stable',
    replacementGuardEn: 'avoid heavy window grids, boxed panes, generic bedroom, plain wall, studio backdrop, outdoor scene, or unrelated hotel room',
    desc: '高級飯店房間、床面前景、超大片連續落地玻璃牆與紐約式高樓城市背景構成的窗景 set。',
    aspectRatioId: '1:1',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'indoor', 'hotel_window_set', 'square_set'] },
  },
  {
    id: 'luxury-hotel-window-mount-fuji-spring',
    zh: '高級飯店落地窗富士山春景',
    setGroupId: 'hotel-window',
    en: 'The portrait takes place inside a real-scale luxury hotel room editorial set, not a flat backdrop and not a tight subject portrait. Treat the fixed set as the primary composition: an oversized near-wall-to-wall panoramic floor-to-ceiling glass wall dominates the back plane as one broad mostly uninterrupted glass plane overlooking a spring Mount Fuji landscape. The glass should feel open, expansive, and lightly reflective, with only a few slim structural seams near the far edges if needed. Avoid grid-like window panels, heavy black frames, boxed window sections, many repeated dividers, balcony doors, or apartment-style segmented windows. A hotel bed with soft white rumpled bedding occupies the lower room plane, with pillows, a bedside table, warm hotel lamp, curtain edges, and subtle room-depth props as readable interaction anchors. Outside the glass, Mount Fuji is the dominant distant landscape anchor, with residual snow on the summit, clean blue spring sky, fresh green foothills, small lakeside or town rooftops, and subtle cherry blossoms or spring foliage that never cover or replace the mountain. Use a medium-wide editorial camera position approximately 3 to 5 meters away from the bed and glass wall, pulled back enough to show the subject inside the room and preserve the subject-to-bed and subject-to-window scale. The viewpoint may vary around the same fixed Fuji hotel-window set, but must not replace the set, collapse into a tight portrait, or lose the panoramic glass wall, Mount Fuji, bed or bedding, and warm bedside lamp as recognizable anchors',
    integrityEn: 'preserve anchors: broad panoramic glass wall, Mount Fuji spring landscape, bed/bedding foreground, bedside lamp/table zone; keep their relative positions stable',
    replacementGuardEn: 'avoid heavy window grids, boxed panes, generic city skyline, plain wall, studio backdrop, outdoor mountain scene, onsen ryokan, or unrelated hotel room',
    desc: '高級飯店房間、床面前景、超大片連續落地玻璃牆與春季富士山、綠意山麓、湖畔或小鎮屋頂構成的窗景 set。',
    aspectRatioId: '1:1',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'indoor', 'hotel_window_set', 'mount_fuji_view_set', 'spring_set', 'square_set'] },
  },
  {
    id: 'luxury-hotel-window-mount-fuji-winter',
    zh: '高級飯店落地窗富士山冬景',
    setGroupId: 'hotel-window',
    en: 'The portrait takes place inside a real-scale luxury hotel room editorial set, not a flat backdrop and not a tight subject portrait. Treat the fixed set as the primary composition: an oversized near-wall-to-wall panoramic floor-to-ceiling glass wall dominates the back plane as one broad mostly uninterrupted glass plane overlooking a winter Mount Fuji landscape. The glass should feel open, expansive, and lightly reflective, with only a few slim structural seams near the far edges if needed. Avoid grid-like window panels, heavy black frames, boxed window sections, many repeated dividers, balcony doors, or apartment-style segmented windows. A hotel bed with soft white rumpled bedding occupies the lower room plane, with pillows, a bedside table, warm hotel lamp, curtain edges, and subtle room-depth props as readable interaction anchors. Outside the glass, snow-covered Mount Fuji is the dominant distant landscape anchor, with cold clear air, blue-white winter daylight, snowy foothills or village rooftops, and quiet pale sky depth while the warm hotel interior remains readable. Use a medium-wide editorial camera position approximately 3 to 5 meters away from the bed and glass wall, pulled back enough to show the subject inside the room and preserve the subject-to-bed and subject-to-window scale. The viewpoint may vary around the same fixed Fuji hotel-window set, but must not replace the set, collapse into a tight portrait, or lose the panoramic glass wall, snow-covered Mount Fuji, bed or bedding, and warm bedside lamp as recognizable anchors',
    integrityEn: 'preserve anchors: broad panoramic glass wall, snow-covered Mount Fuji winter landscape, bed/bedding foreground, bedside lamp/table zone; keep their relative positions stable',
    replacementGuardEn: 'avoid heavy window grids, boxed panes, generic city skyline, plain wall, studio backdrop, outdoor snowfield, ski resort, onsen ryokan, or unrelated hotel room',
    desc: '高級飯店房間、床面前景、超大片連續落地玻璃牆與冬季積雪富士山、冷白空氣、雪地山麓或村落屋頂構成的窗景 set。',
    aspectRatioId: '1:1',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'indoor', 'hotel_window_set', 'mount_fuji_view_set', 'winter_set', 'square_set'] },
  },
  {
    id: 'retro-tile-bathtub',
    zh: '復古磁磚浴室浴缸',
    en: 'The portrait takes place inside a real-scale vintage bathroom editorial set, not a flat backdrop and not a tight subject portrait. Treat the fixed set as the primary composition: a freestanding clawfoot bathtub remains the main horizontal fixture across the lower room plane, with the visible wet tile floor beneath and in front of the bathtub, tub feet, tub rim, and full outer tub wall remaining readable from the selected camera angle. A flat aged tile-and-plaster bathroom wall fills the back plane, with a porcelain sink or vanity on one side, a mirror above the sink, chrome faucet and shower hardware, wall lamp, folded towels, bath bottles, a small wooden stool, foam or water surface, subtle steam, small puddles, water trails, and floor reflections as readable interaction anchors. Subject wetness condition: fully soaked from head to toe with wet hair, damp skin, and water-clinging wardrobe or bare skin, and the surrounding bathroom can also feel wet with puddles and reflected practical light. Use a medium-wide editorial camera position approximately 2.5 to 4 meters away from the bathtub, pulled back enough to keep the full bathtub body, tub feet, wet floor plane, sink or vanity, and mirror visible where possible while preserving subject-to-bathtub scale. The selected camera angle and orbit may vary the viewpoint around the same fixed bathtub set, but must not replace the set, collapse into a tight portrait, shoot from inside the tub, or lose the bathtub, wet floor, tiled wall, sink, and mirror as recognizable anchors',
    integrityEn: 'preserve anchors: horizontal clawfoot bathtub, visible wet floor, aged tile wall, sink/mirror side zone, bath-prop foreground; keep their relative positions stable',
    replacementGuardEn: 'avoid shower room, pool, spa lobby, bedroom, plain studio backdrop, unrelated bathroom, inside-tub POV, low tub-edge POV, dutch tilt, or tight crop losing the tub body or wet floor',
    desc: '真實比例復古磁磚浴室、正面橫置爪足浴缸、濕地板、洗臉台、鏡子、壁燈、毛巾與瓶罐構成的浴室 set。',
    aspectRatioId: '1:1',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'indoor', 'bathtub_set', 'square_set'] },
  },
  {
    id: 'seaside-slope-railway-crossing',
    zh: '海邊坡道平交道',
    setGroupId: OUTDOOR_FIXED_SET_GROUP_ID,
    allowsCameraVariation: false,
    sharedStructureEn: OUTDOOR_FIXED_COMPOSITION_SHARED_STRUCTURE_EN,
    en: 'The portrait takes place within a real-scale outdoor coastal downhill-road fixed composition set, not a generic beach scene and not a tight subject portrait. Treat the fixed set as the primary composition: the camera is positioned near the upper slope, looking downhill along the road plane toward the ocean horizon. A railway crossing gate cuts across the lower-middle frame, with crossing arms, signal posts, striped warning signs, sloped asphalt, lane marks, roadside utility poles, overhead wires, seaside town rooftops, small building edges, distant shoreline, open sky area, and ocean horizon as stable anchors. Sky color, cloud shape, sun strength, water brightness, and weather mood are controlled by the selected ambient light and subject-light options, not by this fixed set. Keep the road, railway crossing, wires, town edges, and ocean depth readable even when the subject moves or crops into the foreground',
    integrityEn: 'preserve anchors: downhill road plane, railway crossing gate, roadside poles and overhead wires, seaside town edges, ocean horizon; keep their relative positions stable',
    replacementGuardEn: 'avoid generic beach, train station, train-dominant scene, city intersection, cafe, indoor set, or unrelated coastal road',
    desc: '海邊坡道、道路平面、平交道柵欄與號誌、電線桿、架空線、遠方海平線構成的戶外固定取景 set。',
    aspectRatioId: '9:16',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'outdoor', 'coastal_set', 'railway_crossing_set', 'vertical_set'] },
  },
  {
    id: 'seaside-stair-alley',
    zh: '海邊階梯小巷',
    setGroupId: OUTDOOR_FIXED_SET_GROUP_ID,
    allowsCameraVariation: false,
    sharedStructureEn: OUTDOOR_FIXED_COMPOSITION_SHARED_STRUCTURE_EN,
    en: 'The portrait takes place within a real-scale outdoor descending seaside stair-alley fixed composition set, not a generic beach scene and not a tight subject portrait. Treat the fixed set as the primary composition: the camera is positioned near the upper stairs, looking down the stair alley toward the ocean horizon. Descending pale stairs form the foreground and midground path toward the sea, with white or light stucco side walls, narrow building edges, balcony fragments, handrails, potted plants or hydrangeas, overhead wires, distant shoreline, open sky area, and ocean horizon as stable anchors. Sky color, cloud shape, sun strength, water brightness, and weather mood are controlled by the selected ambient light and subject-light options, not by this fixed set. Keep the stair corridor, side walls, rails, plants, wires, and ocean depth readable even when the subject moves or crops into the foreground',
    integrityEn: 'preserve anchors: descending stairway, pale side walls, handrails, potted plants or hydrangeas, overhead wires, ocean horizon; keep their relative positions stable',
    replacementGuardEn: 'avoid indoor staircase, generic beach, city alley without stairs, cafe, plain street, train crossing, or unrelated stairway',
    desc: '海邊階梯小巷、白色或淺色牆面、扶手、盆栽或繡球花、架空線與遠方海平線構成的戶外固定取景 set。',
    aspectRatioId: '9:16',
    meta: { tags: ['fixed_composition_set', 'single_subject_only', 'outdoor', 'coastal_set', 'stair_alley_set', 'vertical_set'] },
  },
];

export const FIXED_SET_POSITION_OPTIONS = [
  { id: 'none', zh: '全無', en: 'none', desc: '不指定固定場景內的人物位置。', meta: { tags: ['none'] } },
  {
    id: 'sofa-free-interaction',
    setId: 'concrete-wall-chesterfield-sofa',
    setGroupId: 'sofa-lounge',
    zh: '自由場景互動',
    en: 'subject placement can vary across one primary zone within the fixed sofa set: sofa seating plane, floor plane in front of the sofa, coffee-table foreground, armrest edge, wall-side space, decorative side area, off-center negative space, or close foreground layer. The sofa can support the subject or remain a background architecture anchor. Choose one secondary interaction anchor such as the coffee table edge, art book, cup, lamp light, cushion, armrest, wall surface, side decor, floor plane, or foreground negative space. Avoid defaulting every result to a centered seated sofa pose',
  },
  {
    id: 'sofa-foreground',
    setId: 'concrete-wall-chesterfield-sofa',
    setGroupId: 'sofa-lounge',
    zh: '近鏡頭沙發前方',
    en: 'subject in the foreground in front of the sofa, with the sofa becoming a background layer; standing, crouching, floor sitting, or close-lens behavior can be model-decided',
  },
  {
    id: 'sofa-seat-center',
    setId: 'concrete-wall-chesterfield-sofa',
    setGroupId: 'sofa-lounge',
    zh: '沙發座面中央',
    en: 'subject placed on the sofa seat plane; sitting, lounging, half-reclining, lying, or leaning on an armrest can be model-decided',
  },
  {
    id: 'sofa-wall-back',
    setId: 'concrete-wall-chesterfield-sofa',
    setGroupId: 'sofa-lounge',
    zh: '沙發後方靠牆',
    en: 'subject near the wall behind or around the sofa, with the sofa as a horizontal foreground anchor; standing, wall-leaning, or forward-leaning behavior can be model-decided',
  },
  {
    id: 'sofa-armrest-foreground-occlusion',
    setId: 'concrete-wall-chesterfield-sofa',
    setGroupId: 'sofa-lounge',
    zh: '沙發扶手前景遮擋',
    en: 'subject partly hidden by the sofa armrest or leather cushion edge in the foreground; foreground occlusion, partial body crop, or close-lens layering can be model-decided',
  },
  {
    id: 'sofa-floor-off-center',
    setId: 'concrete-wall-chesterfield-sofa',
    setGroupId: 'sofa-lounge',
    zh: '沙發地面偏離中心',
    en: 'subject on the floor plane near the sofa but off center, allowing asymmetrical spacing, cropped limbs, or casual distance from the sofa without prescribing an exact pose',
  },
  {
    id: 'hotel-free-interaction',
    setId: 'luxury-hotel-window-nyc',
    setGroupId: 'hotel-window',
    zh: '自由場景互動',
    en: 'subject placement can vary across one primary zone within the fixed hotel-window set: bed surface, bed edge, window-side floor plane, bedside-table side, curtain edge, pillow foreground, rumpled-bedding foreground, close foreground layer, or off-center negative space. The bed can support the subject or remain a foreground or side architecture anchor. Choose one secondary interaction anchor such as bedding, pillow, open book, wine glass, warm lamp, bedside table, curtain, glass reflection, exterior window view, or room floor. Avoid defaulting every result to a centered bed pose',
  },
  {
    id: 'hotel-bed-foreground',
    setId: 'luxury-hotel-window-nyc',
    setGroupId: 'hotel-window',
    zh: '近鏡頭床面前景',
    en: 'subject close to the camera or bed foreground; the exterior window view can be partially blocked or softened',
  },
  {
    id: 'hotel-bed-window-side',
    setId: 'luxury-hotel-window-nyc',
    setGroupId: 'hotel-window',
    zh: '床邊靠窗',
    en: 'subject around the bed edge or window-side mid-plane; body, bedding, glass, and exterior view depth can all remain readable',
  },
  {
    id: 'hotel-window-silhouette',
    setId: 'luxury-hotel-window-nyc',
    setGroupId: 'hotel-window',
    zh: '窗前景觀剪影',
    en: 'subject near the floor-to-ceiling window; the exterior view becomes the dominant background, allowing profile, back-view, window-gazing, or silhouette-like behavior',
  },
  {
    id: 'hotel-window-frame-close',
    setId: 'luxury-hotel-window-nyc',
    setGroupId: 'hotel-window',
    zh: '近鏡頭窗框邊緣',
    en: 'subject very near the lens along the window-frame edge, allowing partial face, shoulder, hair, or half-body crop while the hotel window view remains a recognizable layer',
  },
  {
    id: 'hotel-bedding-foreground-occlusion',
    setId: 'luxury-hotel-window-nyc',
    setGroupId: 'hotel-window',
    zh: '床單前景遮擋',
    en: 'soft bedding or pillow shapes become a foreground occlusion layer in front of the subject, with the body distance and exact interaction left to the image model',
  },
  {
    id: 'bathtub-free-interaction',
    setId: 'retro-tile-bathtub',
    zh: '自由場景互動',
    en: 'subject placement can vary across one primary zone within the fixed bathtub set: inside the bathtub, on the bathtub rim, beside the tub on the wet floor, near the sink and mirror, by the chrome faucet hardware, stool-side foreground, towel foreground, foam-covered water surface, close foreground layer, or off-center negative space. The bathtub can contain the subject or remain the central fixture anchor. Choose one secondary interaction anchor such as tub rim, foam, water surface, puddle reflection, sink, mirror, faucet hardware, towel, bath bottle, stool, or wet floor. Avoid defaulting every result to a centered soaking pose',
  },
  {
    id: 'bathtub-center',
    setId: 'retro-tile-bathtub',
    zh: '浴缸內中央',
    en: 'subject in the middle of the bathtub, surrounded by foam and tub edges; face and upper body can remain the main portrait anchor',
  },
  {
    id: 'bathtub-low-foreground',
    setId: 'retro-tile-bathtub',
    zh: '浴缸前景遮擋',
    en: 'bathtub rim, foam, water surface, towels, bottles, or partial body forms may create lower foreground occlusion and focus variation while the camera remains eye-level and frontal',
  },
  {
    id: 'bathtub-rim-edge',
    setId: 'retro-tile-bathtub',
    zh: '浴缸邊緣',
    en: 'subject close to the bathtub edge; sitting on the rim, holding the rim, or leaning from inside the tub can be model-decided',
  },
  {
    id: 'bathtub-rim-close-crop',
    setId: 'retro-tile-bathtub',
    zh: '浴缸邊近鏡頭裁切',
    en: 'subject very close to the camera at the bathtub rim, allowing partial face, shoulder, knees, feet, or torso fragments to enter the foreground without prescribing exact pose',
  },
  {
    id: 'bathtub-foam-foreground-occlusion',
    setId: 'retro-tile-bathtub',
    zh: '泡泡前景遮擋',
    en: 'foam bubbles and water surface create foreground occlusion around the subject, allowing parts of the body or face to be softened, hidden, or out of focus',
  },
  {
    id: 'crossing-road-free-interaction',
    setId: 'seaside-slope-railway-crossing',
    zh: '自由場景互動',
    en: 'subject placement can vary within the fixed coastal crossing set: road foreground, crossing-gate side, slope midground, roadside edge, building-side margin, utility-pole side, or close foreground layer. Choose one interaction anchor such as the road markings, crossing barrier, signal post, guardrail, utility pole, wall edge, or ocean-facing downhill view while keeping the crossing and sea readable',
  },
  {
    id: 'crossing-gate-side',
    setId: 'seaside-slope-railway-crossing',
    zh: '坡道平交道旁',
    en: 'subject near the railway crossing gate or signal-side edge, with the downhill road, crossing arms, overhead wires, and ocean horizon still visible as the fixed composition',
  },
  {
    id: 'crossing-road-foreground',
    setId: 'seaside-slope-railway-crossing',
    zh: '坡道路面前景',
    en: 'subject on or near the upper road foreground, allowing closer body scale or partial crop while the crossing gate, sloping road, and ocean direction remain readable',
  },
  {
    id: 'crossing-mid-slope',
    setId: 'seaside-slope-railway-crossing',
    zh: '坡道中段',
    en: 'subject in the mid-slope road plane below the camera position, integrated with the downhill depth toward the crossing and ocean horizon without changing the fixed viewpoint',
  },
  {
    id: 'stair-alley-free-interaction',
    setId: 'seaside-stair-alley',
    zh: '自由場景互動',
    en: 'subject placement can vary within the fixed seaside stair-alley set: upper stair foreground, mid-stairs, railing side, wall-side edge, potted-plant side, lower alley depth, or close foreground layer. Choose one interaction anchor such as the handrail, stair edge, side wall, potted plant, hydrangeas, overhead wires, or ocean-facing downhill view while keeping the stair corridor and sea readable',
  },
  {
    id: 'stair-upper-foreground',
    setId: 'seaside-stair-alley',
    zh: '階梯上方前景',
    en: 'subject near the upper stair foreground close to the camera, allowing partial crop or casual foreground presence while the descending stairway and ocean horizon remain recognizable',
  },
  {
    id: 'stair-mid-railing',
    setId: 'seaside-stair-alley',
    zh: '階梯中段欄杆旁',
    en: 'subject around the mid-stairs near a handrail, with pale side walls, stair depth, overhead wires, and ocean horizon held in the same fixed composition',
  },
  {
    id: 'stair-wall-side',
    setId: 'seaside-stair-alley',
    zh: '牆面小巷側邊',
    en: 'subject beside the pale stucco wall or narrow building edge, letting the stairs and railings continue downhill toward the ocean in the background',
  },
];

export const FIXED_SET_BACKGROUND_STATE_OPTIONS = [
  { id: 'none', zh: '全無', en: 'none', meta: { tags: ['none'] } },
  {
    id: 'outdoor-empty',
    setGroupId: OUTDOOR_FIXED_SET_GROUP_ID,
    zh: '空無一人',
    en: 'background life state: the outdoor fixed set is empty of pedestrians, vehicles, and extra activity, like a quiet location portrait with the scene architecture unobstructed',
  },
  {
    id: 'outdoor-sparse-pedestrians',
    setGroupId: OUTDOOR_FIXED_SET_GROUP_ID,
    zh: '稀疏路人',
    en: 'background life state: a few distant pedestrians may appear as small background life details, never competing with the main subject or changing the fixed scene layout',
  },
  {
    id: 'outdoor-lived-in-moment',
    setGroupId: OUTDOOR_FIXED_SET_GROUP_ID,
    zh: '普通生活瞬間',
    en: 'background life state: sparse distant people, subtle local movement, or tiny everyday traces may appear in the fixed outdoor set, keeping a normal life-photo feeling without crowding the frame',
  },
  {
    id: 'crossing-clear',
    setId: 'seaside-slope-railway-crossing',
    zh: '清空平交道',
    en: 'railway crossing state: the crossing is clear with no train passing, the barrier, rails, road plane, and ocean-facing downhill view remain unobstructed',
  },
  {
    id: 'crossing-train-passing',
    setId: 'seaside-slope-railway-crossing',
    zh: '電車經過中',
    en: 'railway crossing state: one local train may pass across the railway crossing as a middle-distance life event, but it must not become a train station scene, dominate the frame, or hide the road, crossing gate, wires, and ocean horizon',
  },
  {
    id: 'crossing-light-traffic',
    setId: 'seaside-slope-railway-crossing',
    zh: '少量生活車輛',
    en: 'background life state: one or two small distant cars, scooters, or bicycles may appear on the road or near the crossing, keeping a quiet everyday coastal-town feeling without crowding the scene',
  },
];

export const FIXED_SET_CAPTURE_MODE_OPTIONS = [
  { id: 'none', zh: '全無', en: 'none', meta: { tags: ['none'] } },
  {
    id: 'photographer-shot',
    zh: '攝影師拍攝',
    en: 'photographer-shot fixed set portrait, subject arranged within the selected set, fixed composition remains readable, face and wardrobe generally clear where framing allows',
    meta: { tags: ['fixed_set_photographer_shot'] },
  },
  {
    id: 'natural-self-shot',
    zh: '自然自拍感',
    en: 'self-shot social composition feeling, subject may move close to the lens, off-center partial face or half-body crop allowed, fixed set may remain only as recognizable background fragments, no visible phone required',
    meta: { tags: ['fixed_set_self_shot'] },
  },
  {
    id: 'imperfect-self-shot',
    zh: '失控自拍感',
    en: 'imperfect self-shot camera behavior, focus may fall on the background or set objects instead of the face, subject may be slightly blurred or partially cropped, fixed set may remain only as recognizable background fragments, casual accidental framing, real social snapshot imperfection, no visible phone required',
    meta: { tags: ['fixed_set_self_shot', 'fixed_set_imperfect_focus'] },
  },
];

export const FIXED_SET_PERFORMANCE_STATE_OPTIONS = [
  { id: 'none', zh: '全無', en: 'none', meta: { tags: ['none'] } },
  {
    id: 'model-natural',
    zh: '模型自然發揮',
    en: 'let the image model choose a natural body attitude and expression that fits the selected fixed set position and capture mode',
  },
  {
    id: 'confident-powerful',
    zh: '自信力量感',
    en: 'confident powerful presence, strong self-possessed attitude, assertive body energy, direct control of the frame without specifying exact limb placement',
  },
  {
    id: 'lazy-drained',
    zh: '慵懶無力感',
    en: 'lazy drained presence, softened body energy, relaxed weight sinking into the set, unforced tired attitude without specifying exact limb placement',
  },
  {
    id: 'detached-cool',
    zh: '冷淡疏離感',
    en: 'detached cool presence, emotionally distant attitude, minimal outward reaction, restrained body energy without specifying exact limb placement',
  },
  {
    id: 'playful-provocative',
    zh: '俏皮挑釁感',
    en: 'playful provocative presence, teasing confidence, mischievous frame awareness, lively social energy without specifying exact limb placement',
  },
  {
    id: 'quiet-vulnerable',
    zh: '安靜脆弱感',
    en: 'quiet vulnerable presence, softened guarded emotion, delicate inner tension, small protective body energy without specifying exact limb placement',
  },
  {
    id: 'urban-fatigue',
    zh: '都市疲憊感',
    en: 'urban fatigue presence, late-night city exhaustion, heavy relaxed energy, candid tired attitude without specifying exact limb placement',
  },
  {
    id: 'dreamlike-dazed',
    zh: '夢遊恍神感',
    en: 'dreamlike dazed presence, slightly absent focus, half-awake social snapshot mood, drifting body energy without specifying exact limb placement',
  },
  {
    id: 'elegant-restrained',
    zh: '優雅克制感',
    en: 'elegant restrained presence, composed quiet poise, controlled emotion, refined low-key body energy without specifying exact limb placement',
  },
  {
    id: 'chaotic-candid',
    zh: '失控隨性感',
    en: 'chaotic candid presence, accidental spontaneous attitude, loose unplanned body energy, imperfect social snapshot timing without specifying exact limb placement',
  },
];
