/**
 * Deterministic target scenarios for fixed-framing derived prompts.
 *
 * Phase 1 keeps these fixtures data-only. Later phases consume the same cases
 * when the shared derived renderer and public extra prompts are activated.
 */

export const FIXED_FRAMING_DERIVED_PROMPT_FIXTURES = Object.freeze([
  Object.freeze({
    id: 'chest-up-normal-separates-pose-scene-imaging',
    seed: 'fixed-framing-chest-normal-v1',
    coverage: Object.freeze(['single', 'chestUpPortrait', 'normalWardrobe', 'pose', 'scene', 'imaging']),
    locks: Object.freeze({
      subjectCount: '1',
      framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
      angleId: { byZh: '平視高度鏡頭' },
      orbitId: { byZh: '左前 45 度' },
      bodyTypeId: { byZh: '性感曲線身形' },
      topId: { byZh: '棉質細肩背心' },
      pantsId: { byZh: '直筒牛仔褲' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '自然站姿' },
      poseHandId: { byZh: '單手摸下巴' },
      poseHeadId: { byZh: '頭部微微側傾' },
      poseAnchorId: { byZh: '肩背倚靠現有垂直面' },
      locationId: { byZh: '室內：英倫復古窗邊房間' },
      styleId: { byZh: '市橋織江｜透明自然低飽和' },
      lensId: { byZh: '85mm 中長焦 (人像鏡皇)' },
      lightingId: { byZh: '室內窗邊日光' },
      lightDirectionId: { byZh: '側向柔光' },
    }),
    expected: Object.freeze({
      outputKey: 'chestUpPortrait',
      aspectRatio: '4:5',
      preserveGroups: Object.freeze(['faceIdentity', 'hair', 'chestBody', 'upperWardrobe', 'projectedCanonicalPose', 'compactSourceScene', 'lighting', 'photographyAndImaging']),
      omitWardrobeRoles: Object.freeze(['bottom', 'legwear', 'shoes', 'bag']),
      preserveRawLockKeys: Object.freeze(['framingId', 'bodyTypeId', 'topId', 'pantsId', 'poseBaseId', 'poseArrangementId', 'poseHandId', 'poseHeadId', 'poseAnchorId', 'locationId', 'styleId', 'lensId']),
    }),
  }),
  Object.freeze({
    id: 'face-special-outfit-visible-neckline',
    seed: 'fixed-framing-face-special-outfit-v1',
    coverage: Object.freeze(['single', 'facialCloseupPortrait', 'specialOutfit', 'upperGarment', 'scene', 'imaging']),
    locks: Object.freeze({
      subjectCount: '1',
      framingId: { byZh: '牛仔中景 (Cowboy Shot)' },
      specialOutfitId: { byZh: '酒紅格紋吊帶牛仔短裙長靴造型' },
      locationId: { byZh: '室內：古書二手書店' },
      lensId: { byZh: '105mm 中長焦' },
      lightingId: { byZh: '室內窗邊日光' },
    }),
    expected: Object.freeze({
      outputKey: 'facialCloseupPortrait',
      aspectRatio: '1:1',
      upperGarmentSource: 'specialOutfit',
      preserveGroups: Object.freeze(['faceIdentity', 'hair', 'upperGarmentNeckline', 'faceAccessories', 'compactSourceScene', 'lighting', 'photographyAndImaging']),
      omitGroups: Object.freeze(['body', 'pose']),
      omitWardrobeRoles: Object.freeze(['bottom', 'legwear', 'shoes', 'bag']),
      preserveRawLockKeys: Object.freeze(['framingId', 'specialOutfitId', 'locationId', 'lensId']),
    }),
  }),
  Object.freeze({
    id: 'chest-up-outfit-preset-upper-structure',
    seed: 'fixed-framing-chest-outfit-preset-v1',
    coverage: Object.freeze(['single', 'chestUpPortrait', 'outfitPreset', 'upperGarment', 'scene', 'imaging']),
    locks: Object.freeze({
      subjectCount: '1',
      framingId: { byZh: '半臉傾斜特寫' },
      outfitPresetId: { byZh: '套裝：春日巴黎亞麻長褲' },
      locationId: { byZh: '室內：Y2K 復古房間' },
      styleId: { byZh: '石田真澄｜柔亮底片空氣感' },
    }),
    expected: Object.freeze({
      outputKey: 'chestUpPortrait',
      aspectRatio: '4:5',
      upperGarmentSource: 'outfitPreset',
      preserveGroups: Object.freeze(['faceIdentity', 'hair', 'chestBody', 'upperGarment', 'compactSourceScene', 'photographyAndImaging']),
      omitWardrobeRoles: Object.freeze(['bottom', 'legwear', 'shoes', 'bag']),
      preserveRawLockKeys: Object.freeze(['framingId', 'outfitPresetId', 'locationId', 'styleId']),
    }),
  }),
  Object.freeze({
    id: 'face-dress-neckline-source',
    seed: 'fixed-framing-face-dress-v1',
    coverage: Object.freeze(['single', 'facialCloseupPortrait', 'dress', 'upperGarment', 'scene', 'imaging']),
    locks: Object.freeze({
      subjectCount: '1',
      framingId: { byZh: '中景鏡頭 (Medium Shot)' },
      dressId: { byZh: '連身：短版｜一字領哥德迷你洋裝' },
      locationId: { byZh: '室內：精品飯店房間' },
      lensId: { byZh: '85mm 中長焦 (人像鏡皇)' },
    }),
    expected: Object.freeze({
      outputKey: 'facialCloseupPortrait',
      aspectRatio: '1:1',
      upperGarmentSource: 'dress',
      preserveGroups: Object.freeze(['faceIdentity', 'hair', 'upperGarmentNeckline', 'compactSourceScene', 'photographyAndImaging']),
      omitGroups: Object.freeze(['body', 'pose']),
      omitWardrobeRoles: Object.freeze(['bottom', 'legwear', 'shoes', 'bag']),
      preserveRawLockKeys: Object.freeze(['framingId', 'dressId', 'locationId', 'lensId']),
    }),
  }),
  Object.freeze({
    id: 'face-no-upper-garment-positive-fallback',
    seed: 'fixed-framing-face-fallback-v1',
    coverage: Object.freeze(['single', 'facialCloseupPortrait', 'upperGarmentFallback', 'scene', 'imaging']),
    locks: Object.freeze({
      subjectCount: '1',
      framingId: { byZh: '中景鏡頭 (Medium Shot)' },
      facialFeaturesId: { byZh: '日系清透臉' },
      hairstyleId: { byZh: '齊瀏海圓弧鮑伯' },
      locationId: { byZh: '室內：深邃黑幕' },
    }),
    expected: Object.freeze({
      outputKey: 'facialCloseupPortrait',
      aspectRatio: '1:1',
      upperGarmentSource: 'fallback',
      upperGarmentText: 'a simple opaque crew-neck top',
      preserveGroups: Object.freeze(['faceIdentity', 'hair', 'upperGarmentNeckline', 'compactSourceScene', 'photographyAndImaging']),
      omitGroups: Object.freeze(['body', 'pose']),
      preserveRawLockKeys: Object.freeze(['framingId', 'facialFeaturesId', 'hairstyleId', 'locationId']),
    }),
  }),
  Object.freeze({
    id: 'face-character-card-identity-and-outfit',
    seed: 'fixed-framing-face-character-card-v1',
    coverage: Object.freeze(['single', 'facialCloseupPortrait', 'characterCard', 'upperGarment', 'identityAnchors']),
    locks: Object.freeze({
      subjectCount: '1',
      characterProfileId: 'character-kaori',
      framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
      locationId: { byZh: '室內：莫蘭迪灰背景' },
    }),
    expected: Object.freeze({
      outputKey: 'facialCloseupPortrait',
      aspectRatio: '1:1',
      upperGarmentSource: 'characterCardOutfit',
      preserveGroups: Object.freeze(['facialGeometry', 'eyeSignature', 'noseSignature', 'mouthSignature', 'skinSignature', 'makeup', 'permanentIdentityAnchors', 'hair', 'upperGarmentNeckline', 'compactSourceScene']),
      omitGroups: Object.freeze(['body', 'pose']),
      preserveRawLockKeys: Object.freeze(['characterProfileId', 'framingId', 'locationId']),
    }),
  }),
  Object.freeze({
    id: 'chest-up-fixed-composition-scene-source',
    seed: 'fixed-framing-chest-fixed-scene-v1',
    coverage: Object.freeze(['single', 'chestUpPortrait', 'fixedCompositionScene', 'pose', 'imaging']),
    locks: Object.freeze({
      subjectCount: '1',
      fixedCompositionSetId: { byZh: '暖灰泥黑絲絨工業沙發棚' },
      fixedSetPositionId: { byZh: '自由場景互動' },
      fixedSetCaptureModeId: { byZh: '攝影師拍攝' },
      fixedSetPerformanceStateId: { byZh: '模型自然發揮' },
      topId: { byZh: '棉質細肩背心' },
      poseBaseId: { byZh: '站姿' },
      poseArrangementId: { byZh: '自然站姿' },
    }),
    expected: Object.freeze({
      outputKey: 'chestUpPortrait',
      aspectRatio: '4:5',
      preserveGroups: Object.freeze(['faceIdentity', 'upperWardrobe', 'projectedCanonicalPose', 'fixedSetSceneIdentity', 'fixedSetSourceAnchors', 'lighting', 'photographyAndImaging']),
      omitGroups: Object.freeze(['fixedSetCameraDistance']),
      preserveRawLockKeys: Object.freeze(['fixedCompositionSetId', 'fixedSetPositionId', 'fixedSetCaptureModeId', 'fixedSetPerformanceStateId', 'topId', 'poseBaseId', 'poseArrangementId']),
    }),
  }),
  Object.freeze({
    id: 'face-rear-orbit-derived-view-fallback',
    seed: 'fixed-framing-face-rear-orbit-v1',
    coverage: Object.freeze(['single', 'facialCloseupPortrait', 'viewpointCompatibility', 'selectionPreservation']),
    locks: Object.freeze({
      subjectCount: '1',
      framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
      orbitId: { byZh: '背面 180 度' },
      topId: { byZh: '襯衫' },
      locationId: { byZh: '室內：純潔白幕' },
    }),
    expected: Object.freeze({
      outputKey: 'facialCloseupPortrait',
      aspectRatio: '1:1',
      derivedOrbit: 'frontView',
      preserveGroups: Object.freeze(['faceIdentity', 'upperGarmentNeckline', 'compactSourceScene']),
      omitGroups: Object.freeze(['body', 'pose', 'rearOrbitText']),
      preserveRawLockKeys: Object.freeze(['framingId', 'orbitId', 'topId', 'locationId']),
    }),
  }),
  Object.freeze({
    id: 'duo-fixed-framing-outputs-absent',
    seed: 'fixed-framing-duo-absent-v1',
    coverage: Object.freeze(['duo', 'unsupportedMode', 'selectionPreservation']),
    locks: Object.freeze({
      subjectCount: '2',
      framingId: { byZh: '全身鏡頭 (Full Body Shot)' },
      locationId: { byZh: '室內：現代高樓公寓客廳' },
    }),
    expected: Object.freeze({
      absentOutputKeys: Object.freeze(['facialCloseupPortrait', 'chestUpPortrait']),
      preserveRawLockKeys: Object.freeze(['framingId', 'locationId']),
    }),
  }),
]);

export const HALF_FACE_COMPOSITION_REGRESSION_FIXTURES = Object.freeze([
  Object.freeze({
    id: 'half-face-left-edge',
    seed: 'half-face-left-edge-v1',
    resolvedPlacementId: 'left-edge',
    framingZh: '半臉傾斜特寫',
  }),
  Object.freeze({
    id: 'half-face-right-edge',
    seed: 'half-face-right-edge-v5',
    resolvedPlacementId: 'right-edge',
    framingZh: '半臉傾斜特寫',
  }),
]);
