export const SCENE_CAMERA_CONTROL_ORDER = [
  'sceneAttributeId',
  'locationId',
  'fixedCompositionSetId',
  'fixedSetPositionId',
  'fixedSetCaptureModeId',
  'fixedSetPerformanceStateId',
  'lightingId',
  'lightDirectionId',
  'styleId',
  'cameraSystemId',
  'framingId',
  'angleId',
  'orbitId',
  'lensId',
  'opticalEffectId',
  'filmId',
];
